Repository Njord201/Raytracer, pull requests merged in 2024-05, with the labels that each got.

#28 Create the plane primitive
  include/Math/Vector3D.hpp
  include/Primitives/Plane.hpp
  src/Plugins/Primitives/Makefile
  src/Plugins/Primitives/Plane/Makefile
  src/Plugins/Primitives/Plane/Plane.cpp
  src/Plugins/Primitives/Plane/getInstance.cpp
  src/Plugins/Primitives/Sphere/Sphere.cpp
Labels: plugin

#34 feat: compute the nearest hit value to handle
  src/Core/Primitives/PrimitivesContainer.cpp
Labels: enhancement

#37 Feat/create the renderer class
  include/Camera/Camera.hpp
  include/Renderer.hpp
  src/Core/Camera/Camera.cpp
  src/Core/Makefile
  src/Core/Parser/Scene.cpp
  src/Core/Primitives/PrimitivesContainer.cpp
  src/Core/Renderer.cpp
  src/Core/main.cpp
  src/Plugins/Primitives/Sphere/Makefile
  src/Plugins/Primitives/Sphere/Sphere.cpp
Labels: enhancement, architecture

#40 Feat/compute hit color
  include/Lights/Ambient.hpp
  include/Lights/Directional.hpp
  include/Lights/ILight.hpp
  include/Lights/LightsContainer.hpp
  include/Lights/Point.hpp
  include/Primitives/IPrimitive.hpp
  include/Primitives/Plane.hpp
  include/Primitives/PrimitivesContainer.hpp
  include/Primitives/Sphere.hpp
  src/Core/Lights/LightsContainer.cpp
  src/Core/Primitives/PrimitivesContainer.cpp
  src/Core/Renderer.cpp
  src/Plugins/Lights/Ambient/Ambient.cpp
  src/Plugins/Lights/Ambient/Makefile
  src/Plugins/Lights/Directional/Directional.cpp
  src/Plugins/Lights/Point/Point.cpp
  src/Plugins/Primitives/Plane/Plane.cpp
  src/Plugins/Primitives/Sphere/Makefile
  src/Plugins/Primitives/Sphere/Sphere.cpp
Labels: enhancement, architecture, plugin, math

#43 Feat/handle translation
  include/Math/Vector3D.hpp
  include/RaytracerRules.hpp
  src/Core/Parser/Scene.cpp
  src/Core/Primitives/PrimitivesContainer.cpp
  src/Math/Vector3D.cpp
Labels: enhancement, architecture, plugin, math

#45 38 parse the plane primitive
  include/Parser/Factory.hpp
  include/Primitives/Plane.hpp
  src/Core/Makefile
  src/Core/Parser/Factory.cpp
  src/Core/Parser/Scene.cpp
  src/Plugins/Primitives/Plane/Makefile
  src/Plugins/Primitives/Plane/Plane.cpp
  tests/subject.cfg
Labels: enhancement

#49 Fix hitpoint function in Plane primitive
  include/Primitives/Plane.hpp
  src/Plugins/Primitives/Plane/Plane.cpp
Labels: bug

#56 Feat/compute hit color plane
  src/Plugins/Primitives/Plane/Makefile
  src/Plugins/Primitives/Plane/Plane.cpp
Labels: enhancement

#53 fix: primitive plane if the camera origin is set in the Plane
  src/Plugins/Primitives/Plane/Plane.cpp
Labels: bug

#63 feat: render Scene for gui in sdl
  include/Renderer.hpp
  src/Core/Makefile
  src/Core/Renderer.cpp
  src/Core/main.cpp
Labels: enhancement

#66 Feat/handle drop shadow
  include/Color.hpp
  include/Lights/Ambient.hpp
  include/Lights/Directional.hpp
  include/Lights/ILight.hpp
  include/Lights/LightsContainer.hpp
  include/Lights/Point.hpp
  include/Primitives/Cone.hpp
  include/Primitives/Cylinder.hpp
  include/Primitives/IPrimitive.hpp
  include/Primitives/Plane.hpp
  include/Primitives/PrimitivesContainer.hpp
  include/Primitives/Shadow.hpp
  include/Primitives/Sphere.hpp
  include/RaytracerRules.hpp
  src/Core/Color.cpp
  src/Core/Lights/LightsContainer.cpp
  src/Core/Makefile
  src/Core/Primitives/PrimitivesContainer.cpp
  src/Core/Primitives/Shadow.cpp
  src/Plugins/Lights/Ambient/Ambient.cpp
  src/Plugins/Lights/Ambient/Makefile
  src/Plugins/Lights/Directional/Directional.cpp
  src/Plugins/Lights/Directional/Makefile
  src/Plugins/Lights/Point/Makefile
  src/Plugins/Lights/Point/Point.cpp
  src/Plugins/Primitives/Cone/Cone.cpp
  src/Plugins/Primitives/Cylinder/Cylinder.cpp
  src/Plugins/Primitives/Plane/Plane.cpp
  src/Plugins/Primitives/Sphere/Sphere.cpp
Labels: plugin

#71 fix: visualization of primitives behind camera
  include/Primitives/IPrimitive.hpp
  src/Plugins/Primitives/Cone/Cone.cpp
  src/Plugins/Primitives/Cylinder/Cylinder.cpp
  src/Plugins/Primitives/Sphere/Sphere.cpp
Labels: bug, plugin, math

#69 fix: position of elements in sdl
  src/Core/Renderer.cpp
Labels: bug

#72 refactor: directional light do not illuminate the primitives behind it
  include/Math/Vector3D.hpp
  include/Primitives/IPrimitive.hpp
  src/Core/Primitives/Shadow.cpp
  src/Plugins/Lights/Directional/Directional.cpp
Labels: bug, plugin, math

#78 Feat/handle colored lights
  include/Color.hpp
  include/Lights/Ambient.hpp
  include/Lights/Directional.hpp
  include/Lights/ILight.hpp
  include/Lights/Point.hpp
  src/Core/Color.cpp
  src/Core/Lights/LightsContainer.cpp
  src/Core/Parser/Scene.cpp
  src/Plugins/Lights/Ambient/Ambient.cpp
  src/Plugins/Lights/Directional/Directional.cpp
  src/Plugins/Lights/Point/Point.cpp
  tests/files_examples/colorLight.cfg
Labels: enhancement

#79 Handle rotation for primitives & camera
  include/Math/Vector3D.hpp
  include/Primitives/Cone.hpp
  include/Primitives/Cylinder.hpp
  include/Primitives/Plane.hpp
  include/Primitives/Sphere.hpp
  src/Core/Parser/Scene.cpp
  src/Core/Renderer.cpp
  src/Math/Vector3D.cpp
  src/Plugins/Primitives/Cone/Cone.cpp
  src/Plugins/Primitives/Cylinder/Cylinder.cpp
  src/Plugins/Primitives/Plane/Plane.cpp
  src/Plugins/Primitives/Sphere/Sphere.cpp
  tests/files_examples/subjects/rotation_test.cfg
Labels: enhancement

#80 Added RectangularCuboid Primitive
  include/Math/Vector3D.hpp
  include/Parser/Factory.hpp
  include/Primitives/RectangularCuboid.hpp
  src/Core/Makefile
  src/Core/Parser/Factory.cpp
  src/Core/Parser/Scene.cpp
  src/Math/Vector3D.cpp
  src/Plugins/Primitives/Makefile
  src/Plugins/Primitives/RectangularCuboid/Makefile
  src/Plugins/Primitives/RectangularCuboid/RectangularCuboid.cpp
  src/Plugins/Primitives/RectangularCuboid/getInstance.cpp
  tests/files_examples/subjects/subject2.cfg
Labels: enhancement

#84 Implement the last design pattern
  include/Camera/Camera.hpp
  include/Camera/CameraBuilder.hpp
  include/Parser/Scene.hpp
  src/Core/Camera/Camera.cpp
  src/Core/Camera/CameraBuilder.cpp
  src/Core/Makefile
  src/Core/Parser/Scene.cpp
Labels: enhancement

#88 Added a structure for Octree algorithm
  include/Optimisation/Cube.hpp
  include/Optimisation/OctreeRules.hpp
  include/Primitives/Cone.hpp
  include/Primitives/Cylinder.hpp
  include/Primitives/IPrimitive.hpp
  include/Primitives/Plane.hpp
  include/Primitives/RectangularCuboid.hpp
  include/Primitives/Sphere.hpp
  src/Core/Optimisation/Cube.cpp
  src/Plugins/Primitives/Cone/Cone.cpp
  src/Plugins/Primitives/Cylinder/Cylinder.cpp
  src/Plugins/Primitives/Plane/Plane.cpp
  src/Plugins/Primitives/RectangularCuboid/RectangularCuboid.cpp
  src/Plugins/Primitives/Sphere/Sphere.cpp
Labels: enhancement

#93 Feat/create triangle primitive
  include/Math/Vector3D.hpp
  include/Parser/Factory.hpp
  include/Primitives/Cone.hpp
  include/Primitives/Cylinder.hpp
  include/Primitives/IPrimitive.hpp
  include/Primitives/Plane.hpp
  include/Primitives/PrimitivesContainer.hpp
  include/Primitives/RectangularCuboid.hpp
  include/Primitives/Sphere.hpp
  include/Primitives/Triangle.hpp
  src/Core/Makefile
  src/Core/Parser/Factory.cpp
  src/Core/Parser/Scene.cpp
  src/Core/Primitives/PrimitivesContainer.cpp
  src/Math/Vector3D.cpp
  src/Plugins/Primitives/Cone/Cone.cpp
  src/Plugins/Primitives/Cylinder/Cylinder.cpp
  src/Plugins/Primitives/Makefile
  src/Plugins/Primitives/Plane/Plane.cpp
  src/Plugins/Primitives/RectangularCuboid/RectangularCuboid.cpp
  src/Plugins/Primitives/Sphere/Sphere.cpp
  src/Plugins/Primitives/Triangle/Makefile
  src/Plugins/Primitives/Triangle/Triangle.cpp
  src/Plugins/Primitives/Triangle/getInstance.cpp
  tests/files_examples/triangle.cfg
Labels: enhancement, plugin

#92 Feat/implement the octree algorithm
  include/Optimisation/Cube.hpp
  include/Optimisation/Octree.hpp
  include/Optimisation/OctreeRules.hpp
  include/Primitives/Cone.hpp
  include/Primitives/Cylinder.hpp
  include/Primitives/IPrimitive.hpp
  include/Primitives/Plane.hpp
  include/Primitives/RectangularCuboid.hpp
  include/Primitives/Sphere.hpp
  include/Renderer.hpp
  src/Core/Makefile
  src/Core/Optimisation/Cube.cpp
  src/Core/Optimisation/Octree.cpp
  src/Core/Renderer.cpp
  src/Plugins/Primitives/Cone/Cone.cpp
  src/Plugins/Primitives/Cylinder/Cylinder.cpp
  src/Plugins/Primitives/Plane/Plane.cpp
  src/Plugins/Primitives/RectangularCuboid/RectangularCuboid.cpp
  src/Plugins/Primitives/Sphere/Sphere.cpp
  tests/files_examples/subjects/subject2.cfg
Labels: enhancement

#97 feat: handle diffuse light factor
  src/Plugins/Lights/Ambient/Ambient.cpp
  src/Plugins/Lights/Directional/Directional.cpp
  src/Plugins/Lights/Point/Point.cpp
Labels: plugin

#98 Feat/implement the octree algorithm
  include/Optimisation/Cube.hpp
  include/Optimisation/Octree.hpp
  include/Optimisation/OctreeRules.hpp
  include/Primitives/Cone.hpp
  include/Primitives/Cylinder.hpp
  include/Primitives/IPrimitive.hpp
  include/Primitives/Plane.hpp
  include/Primitives/RectangularCuboid.hpp
  include/Primitives/Sphere.hpp
  include/Primitives/Triangle.hpp
  include/Renderer.hpp
  src/Core/Makefile
  src/Core/Optimisation/Cube.cpp
  src/Core/Optimisation/Octree.cpp
  src/Core/Renderer.cpp
  src/Plugins/Primitives/Cone/Cone.cpp
  src/Plugins/Primitives/Cylinder/Cylinder.cpp
  src/Plugins/Primitives/Plane/Plane.cpp
  src/Plugins/Primitives/RectangularCuboid/RectangularCuboid.cpp
  src/Plugins/Primitives/Sphere/Sphere.cpp
  src/Plugins/Primitives/Triangle/Triangle.cpp
  tests/files_examples/subjects/subject2.cfg
Labels: enhancement

#91 Add antialiasing by supersampling
  include/Camera/Camera.hpp
  include/Camera/CameraBuilder.hpp
  include/Color.hpp
  src/Core/Camera/Camera.cpp
  src/Core/Camera/CameraBuilder.cpp
  src/Core/Color.cpp
  src/Core/Parser/Scene.cpp
  src/Core/Renderer.cpp
  tests/files_examples/subjects/rotation_test.cfg
Labels: enhancement

#102 Feat/handle obj files
  include/Optimisation/OctreeRules.hpp
  include/Parser/Factory.hpp
  include/Parser/ParserObj.hpp
  include/Parser/Scene.hpp
  include/Primitives/Cone.hpp
  include/Primitives/Cylinder.hpp
  include/Primitives/IPrimitive.hpp
  include/Primitives/Mesh.hpp
  include/Primitives/Plane.hpp
  include/Primitives/RectangularCuboid.hpp
  include/Primitives/Sphere.hpp
  include/Primitives/Triangle.hpp
  screenshots/.gitkeep
  screenshots/holycow.ppm
  src/Core/Makefile
  src/Core/Parser/Factory.cpp
  src/Core/Parser/ParserObj.cpp
  src/Core/Parser/Scene.cpp
  src/Plugins/Primitives/Cone/Cone.cpp
  src/Plugins/Primitives/Cylinder/Cylinder.cpp
  src/Plugins/Primitives/Makefile
  src/Plugins/Primitives/Mesh/Makefile
  src/Plugins/Primitives/Mesh/Mesh.cpp
  src/Plugins/Primitives/Mesh/getInstance.cpp
  src/Plugins/Primitives/Plane/Plane.cpp
  src/Plugins/Primitives/RectangularCuboid/RectangularCuboid.cpp
  src/Plugins/Primitives/Sphere/Sphere.cpp
  src/Plugins/Primitives/Triangle/Triangle.cpp
  tests/files_examples/obj.cfg
  tests/obj_files/cow-nonormals.obj
Labels: enhancement

#104 fix: Compilation error, rename Octree to Optimisation
  include/Primitives/Mesh.hpp
  src/Plugins/Primitives/Mesh/Mesh.cpp
Labels: bug

#85 feat/ documentation technical + user
  .gitignore
  Makefile
  doc/doxygen/Doxyfile
  doc/refman.pdf
  doc/technical_documentation.pdf
  doc/technical_documentation_ia-deepl.pdf
  doc/technique_documentation.pdf
  doc/user_documentation.pdf
  doc/user_documentation_ia-deepl.pdf
  doc/utilisateur_documentation.pdf
  include/Parser/Factory.hpp
  include/Parser/Scene.hpp
  tests/files_examples/subjects/rotation_test.cfg
  tests/files_examples/subjects/subject.cfg
  tests/files_examples/subjects/subject2.cfg
Labels: documentation
